export const updatesData = [
    {
        'id': 1,
        'title': 'example 1 title',
        'image': 'src/assets/images/images.jpeg',
        'date': '5 sep',
        'button':'more',
        'text': 'Children’s Home on May 21, 2023, offers an opportunity to witness firsthand the nurturing environment provided to orphaned and vulnerable children. Experience the love, care, and impact being ma',
    },
    {
        'id': 2,
        'title': 'example 2 title',
        'image': 'src/assets/images/download (2).jpeg',
        'date': '6 dec',
        'button':'more',
        'text': 'Children’s Home on May 21, 2023, offers an opportunity to witness firsthand the nurturing environment provided to orphaned and vulnerable children. Experience the love, care, and impact being ma',
    },
    {
        'id': 3,
        'title': 'example 3 title',
        'image': 'src/assets/images/download.jpeg ',
        'date': '6 mar',
        'button':'more',
        'text': 'Children’s Home on May 21, 2023, offers an opportunity to witness firsthand the nurturing environment provided to orphaned and vulnerable children. Experience the love, care, and impact being ma',
    },
    {
        'id': 4,
        'title': 'example 3 title',
        'image': 'src/assets/images/download.jpeg ',
        'date': '6 mar',
        'button':'more',
        'text': 'Children’s Home on May 21, 2023, offers an opportunity to witness firsthand the nurturing environment provided to orphaned and vulnerable children. Experience the love, care, and impact being ma',
    },
    {
        'id': 5,
        'title': 'example 3 title',
        'image': 'src/assets/images/download.jpeg ',
        'date': '6 mar',
        'button':'more',
        'text': 'Children’s Home on May 21, 2023, offers an opportunity to witness firsthand the nurturing environment provided to orphaned and vulnerable children. Experience the love, care, and impact being ma',
    },
]